### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by luodaxu** [AlexKVal/pl-react-webpack-hot#1]
when npm start project ,
 it occors a error as above

**Comment by AlexKVal** [comment]
Hi :smiley: 

I must apologize for not marking it clear that this project is a pure experimental playground,
which is subject to be not working and be deleted at any time :smile: 

May I suggest you these nice resources exactly about your interests :wink:  ?
I believe this project https://github.com/gaearon/react-hot-boilerplate contains exactly what you need.
And these articles are not bad too:
http://jmfurlott.com/setting-up-react-hot-loader/
https://robots.thoughtbot.com/setting-up-webpack-for-react-and-hot-module-replacement

**Comment by luodaxu** [comment]
Hi☺,
It is fine, I am a fun of React and I work in Cisco company,Thanks for your
advice, I will watch u on github~

2015-07-23 3:59 GMT+08:00 Alexander Shemetovsky notifications@github.com:

**Comment by AlexKVal** [comment]
>  I will watch u on github

:blush:  thank you.
